import { useState } from 'react';
import { useAuth } from '../context/AuthContext.jsx';
import { useToast } from '../context/ToastContext.jsx';
import Button from '../components/ui/Button.jsx';
export default function AccountSettings() {
  const { user, updateProfile, changePassword } = useAuth(); const { showToast } = useToast();
  const [profile, setProfile] = useState({ fullName: user?.user_metadata?.full_name || '', email: user?.email || '' });
  const [passwords, setPasswords] = useState({ current: '', next: '', confirm: '' }); const [saving, setSaving] = useState(false);
  const saveProfile = async (e) => { e.preventDefault(); setSaving(true); try { await updateProfile(profile); showToast('Profile updated'); } catch (e) { showToast(e.message || 'Could not update profile', 'error'); } finally { setSaving(false); } };
  const change = async (e) => { e.preventDefault(); if (passwords.next.length < 8) return showToast('New password must be at least 8 characters', 'error'); if (passwords.next !== passwords.confirm) return showToast('Passwords do not match', 'error'); setSaving(true); try { await changePassword(passwords.next); setPasswords({ current: '', next: '', confirm: '' }); showToast('Password changed'); } catch (e) { showToast(e.message || 'Could not change password', 'error'); } finally { setSaving(false); } };
  return <div className="space-y-12 max-w-lg"><div><h2 className="font-display text-2xl mb-6">Profile</h2><form onSubmit={saveProfile} className="space-y-4"><label className="block"><span className="text-xs tracking-wide text-muted mb-1.5 block">Full Name</span><input required value={profile.fullName} onChange={(e) => setProfile((p) => ({ ...p, fullName: e.target.value }))} className="w-full border border-ink/20 px-3 py-2.5 text-sm outline-none focus:border-burgundy" /></label><label className="block"><span className="text-xs tracking-wide text-muted mb-1.5 block">Email</span><input required type="email" value={profile.email} onChange={(e) => setProfile((p) => ({ ...p, email: e.target.value }))} className="w-full border border-ink/20 px-3 py-2.5 text-sm outline-none focus:border-burgundy" /></label><Button type="submit" size="sm" disabled={saving}>Save Changes</Button></form></div><div className="hairline pt-10"><h2 className="font-display text-2xl mb-6">Change Password</h2><form onSubmit={change} className="space-y-4"><input type="password" placeholder="Current Password (optional)" value={passwords.current} onChange={(e) => setPasswords((p) => ({ ...p, current: e.target.value }))} className="w-full border border-ink/20 px-3 py-2.5 text-sm outline-none focus:border-burgundy" /><input required type="password" placeholder="New Password" value={passwords.next} onChange={(e) => setPasswords((p) => ({ ...p, next: e.target.value }))} className="w-full border border-ink/20 px-3 py-2.5 text-sm outline-none focus:border-burgundy" /><input required type="password" placeholder="Confirm New Password" value={passwords.confirm} onChange={(e) => setPasswords((p) => ({ ...p, confirm: e.target.value }))} className="w-full border border-ink/20 px-3 py-2.5 text-sm outline-none focus:border-burgundy" /><Button type="submit" size="sm" disabled={saving}>Update Password</Button></form></div></div>;
}
