import { useEffect, useState } from 'react';
import { MapPin, Plus, Pencil, Trash2 } from 'lucide-react';
import Button from '../components/ui/Button.jsx';
import Modal from '../components/ui/Modal.jsx';
import EmptyState from '../components/ui/EmptyState.jsx';
import { useToast } from '../context/ToastContext.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { addressesApi } from '../lib/api';
import { Spinner } from '../components/ui/LoadingState.jsx';
const emptyAddress = { label: 'Home', fullName: '', address: '', city: '', state: '', postalCode: '', country: 'United States', phone: '', isDefault: false };
const toForm = (a) => ({ id: a.id, label: a.label, fullName: a.full_name || a.fullName || '', address: a.address, city: a.city, state: a.state, postalCode: a.postal_code || a.postalCode || '', country: a.country, phone: a.phone || '', isDefault: Boolean(a.is_default ?? a.isDefault) });
const toDb = (a) => ({ ...(a.id ? { id: a.id } : {}), label: a.label, full_name: a.fullName, address: a.address, city: a.city, state: a.state, postal_code: a.postalCode, country: a.country, phone: a.phone, is_default: a.isDefault });
export default function Addresses() {
  const { user } = useAuth(); const { showToast } = useToast(); const [addresses, setAddresses] = useState([]); const [loading, setLoading] = useState(true); const [modalOpen, setModalOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(emptyAddress);
  useEffect(() => { let alive = true; addressesApi.list(user.id).then((a) => alive && setAddresses(a.map(toForm))).catch((e) => alive && showToast(e.message || 'Could not load addresses', 'error')).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [user, showToast]);
  const openNew = () => { setEditing(null); setForm({ ...emptyAddress }); setModalOpen(true); }; const openEdit = (a) => { setEditing(a.id); setForm({ ...a }); setModalOpen(true); };
  const save = async (e) => { e.preventDefault(); try { const saved = await addressesApi.save(user.id, toDb({ ...form, id: editing })); const normalized = toForm(saved); setAddresses((prev) => editing ? prev.map((a) => a.id === editing ? normalized : a) : [...prev, normalized]); setModalOpen(false); showToast(editing ? 'Address updated' : 'Address added'); } catch (e) { showToast(e.message || 'Could not save address', 'error'); } };
  const remove = async (id) => { try { await addressesApi.remove(user.id, id); setAddresses((p) => p.filter((a) => a.id !== id)); showToast('Address removed'); } catch (e) { showToast(e.message || 'Could not remove address', 'error'); } };
  if (loading) return <div className="py-20 flex justify-center"><Spinner /></div>;
  return <div><div className="flex items-center justify-between mb-6"><h2 className="font-display text-2xl">Saved Addresses</h2><Button size="sm" onClick={openNew}><Plus size={14} /> Add Address</Button></div>{addresses.length === 0 ? <EmptyState icon={MapPin} title="No saved addresses" description="Add an address to speed up checkout next time." /> : <div className="grid sm:grid-cols-2 gap-4">{addresses.map((a) => <div key={a.id} className="border border-ink/10 p-5"><div className="flex items-center justify-between mb-2"><span className="text-xs uppercase tracking-wide text-burgundy font-semibold">{a.label}</span>{a.isDefault && <span className="text-[10px] bg-gold/15 text-gold px-2 py-0.5 rounded-full">Default</span>}</div><p className="text-sm">{a.fullName}</p><p className="text-sm text-muted mt-1 leading-relaxed">{a.address}, {a.city}, {a.state} {a.postalCode}, {a.country}</p><p className="text-sm text-muted mt-1">{a.phone}</p><div className="flex items-center gap-4 mt-4"><button onClick={() => openEdit(a)} className="flex items-center gap-1.5 text-xs"><Pencil size={13} /> Edit</button><button onClick={() => remove(a.id)} className="flex items-center gap-1.5 text-xs"><Trash2 size={13} /> Remove</button></div></div>)}</div>}<Modal open={modalOpen} onClose={() => setModalOpen(false)} title={editing ? 'Edit Address' : 'Add Address'}><form onSubmit={save} className="space-y-3"><input required placeholder="Label" value={form.label} onChange={(e) => setForm((f) => ({ ...f, label: e.target.value }))} className="w-full border border-ink/20 px-3 py-2 text-sm" /><input required placeholder="Full Name" value={form.fullName} onChange={(e) => setForm((f) => ({ ...f, fullName: e.target.value }))} className="w-full border border-ink/20 px-3 py-2 text-sm" /><input required placeholder="Address" value={form.address} onChange={(e) => setForm((f) => ({ ...f, address: e.target.value }))} className="w-full border border-ink/20 px-3 py-2 text-sm" /><div className="grid sm:grid-cols-2 gap-3">{['city','state','postalCode','country','phone'].map((key) => <input key={key} required={key !== 'phone'} placeholder={key} value={form[key]} onChange={(e) => setForm((f) => ({ ...f, [key]: e.target.value }))} className="border border-ink/20 px-3 py-2 text-sm" />)}</div><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={form.isDefault} onChange={(e) => setForm((f) => ({ ...f, isDefault: e.target.checked }))} /> Make default</label><Button type="submit" className="w-full">Save Address</Button></form></Modal></div>;
}
